### ISSUE TITLE
Product Roadmap Feature List

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub#8]
Hi All,

We are always looking to improve the Ultralytics HUB and to provide features that are most useful to our users. 🚀

## In Progress
- [ ] Ultralytics Cloud training with GPU (K80, P4, T4, P100, V100, A100)
- [ ] Plan upgrades to meet your requirements
- [x] Custom Dataset Validation. We are working to improve the validation of your custom datasets to prevent simple errors.
- [x] UI/UX Updates.

## Coming Soon
- [ ] Marketplace. A one stop shop to datasets and models created by other users, or share your creations with the world.
- [ ] Teams. Collaborate within your team by sharing projects, models and datasets privately.
- [X] Public Previews. Share your model publicly with limited access so your friends can see what you have created.
- [x] Resume Training. If your training stops midway resume from the last checkpoint to prevent lost time.
- [ ] Concat Datasets. Combine datasets or create a custom one by selecting only the classes you need from existing datasets.

**Comment by kalenmike** [comment]
We have migrated this issue content over to our project. Please follow https://github.com/orgs/ultralytics/projects/10 for future updates.
